name: AutoClaim

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 4 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Nodejs
      run: |
        sudo apt-get install nodejs -y
        npm install
    - name: Claim rewards
      run: |
        mkdir /home/runner/work/epicgames-freebies-claimer/epicgames-freebies-claimer/.egstore/9d0e8aa2892a9f23fa7f89051a4ae0a05c2c4858c25a86c4e9ebf9060b9a63b2
        npm start {{ secrets.username }} {{ secrets.password }}
    - name: Claim rewards2
      run: |
        npm start {{ secrets.username2 }} {{ secrets.password2 }}
